name: CI

on:
  push:
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run pylint
        run: poetry run pylint src --rcfile=".pylintrc"
        continue-on-error: true
      - name: Run tests
        run: poetry run pytest src/tests
      - name: Run robot tests
        if: always()
        run: poetry run robot src/tests
